language: cpp

os:
  - linux
  - osx
  - windows

dist: xenial

compiler:
  - gcc
  - clang

env:
  - MODE=debug
  - MODE=release

addons:
  apt:
    packages:
      - graphviz
      - bison
      - flex
      - perl
      - libxml2-dev
      - zlib1g-dev
#  choco:
#    packages:
#      - winflexbison

# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi


install:
  - export "PATH=$TRAVIS_BUILD_DIR/bin:$PATH"
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install winflexbison; fi;
  - cp configure.user.dist configure.user
  - ./configure WITH_QTENV=no WITH_OSG=no WITH_OSGEARTH=no
  - make -j4 MODE=$MODE

script:
  - cd test/core; ./runtest
